[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[[redirects]]
  from = "https://dir-a.flamboyant-varahamihira-ce515b.netlify.com/*"
  to = "/dir-a/:splat"
  status = 200

[[redirects]]
  from = "https://dir-b.flamboyant-varahamihira-ce515b.netlify.com/*"
  to = "/dir-b/:splat"
  status = 200
